export const allAirports = [
  {
    id: 1,
    code: "TLV",
    name: "Ben Gurion Intl Airport",
    city: "Tel Aviv",
    country: "Israel",
    lat: 32.0114,
    lng: 34.8866,
  },
  {
    id: 2,
    code: "JFK",
    name: "John F. Kennedy Intl Airport",
    city: "New York",
    country: "USA",
    lat: 40.6413,
    lng: -73.7781,
  },
  {
    id: 3,
    code: "ORD",
    name: "O'Hare Intl Airport",
    city: "Chicago",
    country: "USA",
    lat: 41.9742,
    lng: -87.9073,
  },
  {
    id: 4,
    code: "LAX",
    name: "Los Angeles Intl Airport",
    city: "Los Angeles",
    country: "USA",
    lat: 33.9416,
    lng: -118.4085,
  },
];
