export const flights = [
  {
    id: "LY001",
    airline: "El Al Israel Airlines",
    flightNumber: "LY001",
    origin: {
      code: "TLV",
      name: "Ben Gurion Intl Airport",
      city: "Tel Aviv",
      country: "Israel",
    },
    destination: {
      code: "JFK",
      name: "John F. Kennedy Intl Airport",
      city: "New York",
      country: "USA",
    },
    departureTime: "2025-10-13T00:30:00",
    arrivalTime: "2025-10-13T06:30:00",
    durationMinutes: 720,
    price: { amount: 820, currency: "USD" },
    stops: 0,
    aircraft: "Boeing 787-9",
    terminal: "3",
    date: "2025-10-13",
    baggageAllowance: "23kg + 8kg hand luggage",
  },
  {
    id: "AA145",
    airline: "American Airlines",
    flightNumber: "AA145",
    origin: {
      code: "JFK",
      name: "John F. Kennedy Intl Airport",
      city: "New York",
      country: "USA",
    },
    destination: {
      code: "LAX",
      name: "Los Angeles Intl Airport",
      city: "Los Angeles",
      country: "USA",
    },
    departureTime: "2025-10-14T10:00:00",
    arrivalTime: "2025-10-14T13:00:00",
    durationMinutes: 300,
    price: { amount: 280, currency: "USD" },
    stops: 0,
    aircraft: "Boeing 737-800",
    terminal: "4",
    date: "2025-10-14",
    baggageAllowance: "20kg + 8kg hand luggage",
  },
  {
    id: "DL203",
    airline: "Delta Airlines",
    flightNumber: "DL203",
    origin: {
      code: "LAX",
      name: "Los Angeles Intl Airport",
      city: "Los Angeles",
      country: "USA",
    },
    destination: {
      code: "ORD",
      name: "O'Hare Intl Airport",
      city: "Chicago",
      country: "USA",
    },
    departureTime: "2025-10-15T09:15:00",
    arrivalTime: "2025-10-15T14:00:00",
    durationMinutes: 285,
    price: { amount: 210, currency: "USD" },
    stops: 0,
    aircraft: "Airbus A321",
    terminal: "2",
    date: "2025-10-15",
    baggageAllowance: "23kg + 7kg hand luggage",
  },
  {
    id: "UA400",
    airline: "United Airlines",
    flightNumber: "UA400",
    origin: {
      code: "ORD",
      name: "O'Hare Intl Airport",
      city: "Chicago",
      country: "USA",
    },
    destination: {
      code: "JFK",
      name: "John F. Kennedy Intl Airport",
      city: "New York",
      country: "USA",
    },
    departureTime: "2025-10-16T08:45:00",
    arrivalTime: "2025-10-16T12:00:00",
    durationMinutes: 195,
    price: { amount: 190, currency: "USD" },
    stops: 0,
    aircraft: "Boeing 737 MAX 8",
    terminal: "1",
    date: "2025-10-16",
    baggageAllowance: "23kg + 8kg hand luggage",
  },
  {
    id: "LY316",
    airline: "El Al Israel Airlines",
    flightNumber: "LY316",
    origin: {
      code: "LAX",
      name: "Los Angeles Intl Airport",
      city: "Los Angeles",
      country: "USA",
    },
    destination: {
      code: "TLV",
      name: "Ben Gurion Intl Airport",
      city: "Tel Aviv",
      country: "Israel",
    },
    departureTime: "2025-10-17T18:00:00",
    arrivalTime: "2025-10-18T17:00:00",
    durationMinutes: 960,
    price: { amount: 950, currency: "USD" },
    stops: 0,
    aircraft: "Boeing 787-9",
    terminal: "B",
    date: "2025-10-17",
    baggageAllowance: "2x23kg + 8kg hand luggage",
  },
  {
    id: "AA220",
    airline: "American Airlines",
    flightNumber: "AA220",
    origin: {
      code: "ORD",
      name: "O'Hare Intl Airport",
      city: "Chicago",
      country: "USA",
    },
    destination: {
      code: "LAX",
      name: "Los Angeles Intl Airport",
      city: "Los Angeles",
      country: "USA",
    },
    departureTime: "2025-10-18T14:30:00",
    arrivalTime: "2025-10-18T17:15:00",
    durationMinutes: 285,
    price: { amount: 260, currency: "USD" },
    stops: 0,
    aircraft: "Airbus A320",
    terminal: "3",
    date: "2025-10-18",
    baggageAllowance: "23kg + 8kg hand luggage",
  },
  {
    id: "DL500",
    airline: "Delta Airlines",
    flightNumber: "DL500",
    origin: {
      code: "JFK",
      name: "John F. Kennedy Intl Airport",
      city: "New York",
      country: "USA",
    },
    destination: {
      code: "ORD",
      name: "O'Hare Intl Airport",
      city: "Chicago",
      country: "USA",
    },
    departureTime: "2025-10-19T08:00:00",
    arrivalTime: "2025-10-19T10:15:00",
    durationMinutes: 135,
    price: { amount: 200, currency: "USD" },
    stops: 0,
    aircraft: "Boeing 737-900",
    terminal: "4",
    date: "2025-10-19",
    baggageAllowance: "23kg + 7kg hand luggage",
  },
  {
    id: "UA780",
    airline: "United Airlines",
    flightNumber: "UA780",
    origin: {
      code: "LAX",
      name: "Los Angeles Intl Airport",
      city: "Los Angeles",
      country: "USA",
    },
    destination: {
      code: "JFK",
      name: "John F. Kennedy Intl Airport",
      city: "New York",
      country: "USA",
    },
    departureTime: "2025-10-20T11:45:00",
    arrivalTime: "2025-10-20T20:00:00",
    durationMinutes: 315,
    price: { amount: 295, currency: "USD" },
    stops: 0,
    aircraft: "Boeing 777-200",
    terminal: "B",
    date: "2025-10-20",
    baggageAllowance: "23kg + 8kg hand luggage",
  },
  {
    id: "LY317",
    airline: "El Al Israel Airlines",
    flightNumber: "LY317",
    origin: {
      code: "TLV",
      name: "Ben Gurion Intl Airport",
      city: "Tel Aviv",
      country: "Israel",
    },
    destination: {
      code: "ORD",
      name: "O'Hare Intl Airport",
      city: "Chicago",
      country: "USA",
    },
    departureTime: "2025-10-21T06:00:00",
    arrivalTime: "2025-10-21T14:00:00",
    durationMinutes: 600,
    price: { amount: 880, currency: "USD" },
    stops: 0,
    aircraft: "Boeing 787-9",
    terminal: "3",
    date: "2025-10-21",
    baggageAllowance: "2x23kg + 8kg hand luggage",
  },
  {
    id: "AA201",
    airline: "American Airlines",
    flightNumber: "AA201",
    origin: {
      code: "ORD",
      name: "O'Hare Intl Airport",
      city: "Chicago",
      country: "USA",
    },
    destination: {
      code: "TLV",
      name: "Ben Gurion Intl Airport",
      city: "Tel Aviv",
      country: "Israel",
    },
    departureTime: "2025-10-22T23:30:00",
    arrivalTime: "2025-10-23T18:30:00",
    durationMinutes: 720,
    price: { amount: 910, currency: "USD" },
    stops: 0,
    aircraft: "Boeing 777-300ER",
    terminal: "1",
    date: "2025-10-22",
    baggageAllowance: "2x23kg + 8kg hand luggage",
  },
];
